[package]
edition = "2018"
name = "onefetch"
description = "Git repository summary on your terminal"
version = "2.4.0"
authors = ["o2sh <ossama-hjaji@live.fr>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/o2sh/onefetch"
exclude = ["assets/*.png"]

[package.metadata.deb]
extended-description = """\
Onefetch is a command line tool that displays information about your Git repository directly on your terminal. \
Onefetch supports more than 50 different programming languages. If your language of choice isn't supported: Open up an issue and support will be added. \
"""
depends = "$auto"
section = "utility"
priority = "optional"

[dependencies]
colored= "2.0.0"
git2 = { version = "0.13.18", default-features = false }
tokei = "12.0.0"
askalono = "0.4.3"
bytecount = "0.6.0"
clap = "2.33.3"
strum = { version = "0.19.5", features = ["derive"] }
image = "0.23.10"
regex = "1"
futures = "0.3.6"
tokio = { version = "0.2.22", features = ["full"] }

[target.'cfg(windows)'.dependencies]
ansi_term = "0.12"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.79"
base64 = "0.13.0"

[dev-dependencies]
lazy_static = "1.4"
more-asserts = "0.2"
paste = "1"
